import {
  ArrowUpDown,
  Award,
  Beaker,
  Calendar,
  ChartLine,
  Check,
  ChevronLeft,
  ChevronRight,
  FlaskConical,
  Grid3x3,
  Info,
  List,
  Map,
  MoveVertical,
  Ruler,
  Scale,
  Search,
  Shield,
  Sun,
  Tag,
  Timer,
  Wheat,
  X,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  wheat: Wheat,
  scale: Scale,
  "flask-conical": FlaskConical,
  "line-chart": ChartLine,
  ruler: Ruler,
  "move-vertical": MoveVertical,
  timer: Timer,
  beaker: Beaker,
  sun: Sun,
  award: Award,
  calendar: Calendar,
  shield: Shield,
  tag: Tag,
  search: Search,
  "arrow-up-down": ArrowUpDown,
  info: Info,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  x: X,
  check: Check,
  "grid-3x3": Grid3x3,
  map: Map,
  list: List,
};

export function getIcon(name: string | undefined): LucideIcon | undefined {
  return name ? ICONS[name] : undefined;
}
